name = "sphera"
version = "9.0.0"
license = "GPL-3.0"
author = "AndreaAmicarelliRSE"
copyright = "Copyright (c) 2015-2021, AndreaAmicarelliRSE"

[[executable]]
name = "sphera"
source-dir = "src/Main_algorithm"
main = "sphera.f90"